blank_issues_enabled: false
contact_links:
  - name: Questions and usage support
    url: https://github.com/DYBInh2k5/Credit-Card-Fraud-Detection-Project/discussions
    about: Ask usage questions in Discussions.
